
def Testexc.an_exception() 
   raise "An exception raised from Ruby code"
end

def Testexc.an_error()
   foobarbla()
end

